# Generated by Django 5.1.7 on 2025-04-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('new', 'New'), ('thrift', 'Thrift')], default='new', max_length=6),
        ),
    ]
